#!/bin/sh
set -eu
export PYTHONDONTWRITEBYTECODE=1

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
REPO_ROOT=$(CDPATH= cd -- "$SCRIPT_DIR/../../.." && pwd)
FRONTEND_ROOT="$REPO_ROOT/frontend"
SCS_LOCAL_BACKEND_URL=${SCS_BACKEND_URL:-http://127.0.0.1:8000}
SCS_LOCAL_FRONTEND_HOST=${SCS_FRONTEND_HOST:-127.0.0.1}
SCS_LOCAL_FRONTEND_PORT=${SCS_FRONTEND_PORT:-4173}

python3 "$FRONTEND_ROOT/e2e/local-staging/local_urls.py" "$SCS_LOCAL_BACKEND_URL" --label "backend URL" >/dev/null

cd "$FRONTEND_ROOT"
REACT_APP_BACKEND_URL="$SCS_LOCAL_BACKEND_URL" \
REACT_APP_PREVIEW_MODE=false \
REACT_APP_ALLOW_ANALYTICS=false \
HOST="$SCS_LOCAL_FRONTEND_HOST" \
PORT="$SCS_LOCAL_FRONTEND_PORT" \
BROWSER=none \
CI=true \
exec npm start
